services:
  postgres:
    container_name: postgres
    image: timescale/timescaledb:2.15.1-pg15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      # 🔥 Tu volumen ya existente, NO CAMBIAR
      - tmp_postgres_data:/var/lib/postgresql/data

      # Si tienes scripts de inicialización, déjalos aquí
      # - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - siscom-network
  postgres-backup:
    build:
      context: ./postgres-backup
    container_name: postgres-backup
    depends_on:
      - postgres
    environment:
      TZ: America/Mexico_City
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${BACKUP_DB}
      POSTGRES_USER: ${BACKUP_USER}
      PGPASSWORD: ${BACKUP_PASSWORD}
      S3_BUCKET: ${S3_BUCKET}
      S3_PREFIX: ${S3_PREFIX}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./backups:/backups
    entrypoint: >
      bash -c "
        echo '0 4,16 * * * /app/backup.sh >> /proc/1/fd/1 2>> /proc/1/fd/2' > /etc/cron.d/postgres-backup &&
        chmod 0644 /etc/cron.d/postgres-backup &&
        crontab /etc/cron.d/postgres-backup &&
        cron -f
      "
    networks:
      - siscom-network
    restart: unless-stopped

networks:
  siscom-network:
    external: true

volumes:
  tmp_postgres_data:
    external: true
