services:
  postgres:
    container_name: postgres
    image: timescale/timescaledb:2.15.1-pg15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      # 🔥 Tu volumen ya existente, NO CAMBIAR
      - tmp_postgres_data:/var/lib/postgresql/data

      # Si tienes scripts de inicialización, déjalos aquí
      # - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - siscom-network
  postgres-backup:
    build:
      context: ./postgres-backup
    container_name: postgres-backup
    depends_on:
      - postgres
    environment:
      TZ: America/Mexico_City
      POSTGRES_HOST: postgres
      POSTGRES_DB: siscom-test
      POSTGRES_USER: backup_user
      PGPASSWORD: uzHA6DeW12eFsbaDbDDgqiCtIf9bAik2h4I32nOb5XT
      S3_BUCKET: siscom-postgres-backups-prod
      S3_PREFIX: postgres
      AWS_REGION: us-east-1
    volumes:
      - ./backups:/backups
    entrypoint: >
      bash -c "
        echo '0 4,16 * * * /app/backup.sh >> /proc/1/fd/1 2>> /proc/1/fd/2' > /etc/cron.d/postgres-backup &&
        chmod 0644 /etc/cron.d/postgres-backup &&
        crontab /etc/cron.d/postgres-backup &&
        cron -f
      "
    networks:
      - siscom-network
    restart: unless-stopped

networks:
  siscom-network:
    external: true

volumes:
  tmp_postgres_data:
    external: true
