services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=pgadmin123
      - POSTGRES_DB=siscom-test
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./ddl.sql:/docker-entrypoint-initdb.d/01-ddl.sql:ro
      - ./init.sql:/docker-entrypoint-initdb.d/02-init.sql:ro
      - ./dump-siscom.sql:/docker-entrypoint-initdb.d/03-dump.sql:ro
    ports:
      - "15432:5432"
    networks:
      - siscom-network
    restart: unless-stopped

  postgrest:
    image: postgrest/postgrest:latest
    container_name: postgrest
    environment:
      PGRST_DB_URI: postgres://siscom:siscom@postgres:5432/siscom-test
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_JWT_SECRET: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTYiLCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJyb2xlIjoidGVzdGVyIiwiaWF0IjoxNzM3OTc3NjAwLCJleHAiOjQ3OTM2NDk2MDB9.uT8nA-pUYCikcWiybkBpcnJjsMTY0v2JGxVNZB6ZFKU"
    depends_on:
      - postgres
    ports:
      - "4000:3000"
    networks:
      - siscom-network
    restart: unless-stopped

networks:
  siscom-network:
    external: true

volumes:
  postgres_data:
