-- Crear usuario normal
CREATE USER siscom WITH PASSWORD 'siscom';

-- Dar permisos completos sobre la BD
GRANT ALL PRIVILEGES ON DATABASE "siscom-test" TO siscom;

-- Permisos sobre tablas EXISTENTES
GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO siscom;

-- Permisos sobre SEQUENCES (MUY importante)
GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA public
TO siscom;

-- Para FUTURAS tablas
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLES TO siscom;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT
ON SEQUENCES TO siscom;

-- Crear rol anónimo para PostgREST
CREATE ROLE web_anon NOLOGIN;

-- privilegios
GRANT USAGE ON SCHEMA public TO web_anon;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO web_anon;


GRANT CONNECT ON DATABASE "siscom-test" TO siscom;
GRANT USAGE ON SCHEMA public TO siscom;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO siscom;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO siscom;